version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    image: ai-ingest-mern-backend:local
    environment:
      - NODE_ENV=development
      - PORT=4001
      - MONGODB_URI=mongodb://mongo:27017/ai_ingest
      - SUPABASE_JWKS_URL=${SUPABASE_JWKS_URL}
      - CORS_ORIGIN=http://localhost:5173
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4001:4001"
    depends_on:
      - mongo
volumes:
  mongo_data:
